export const copy = {
  appName: "书单",
  tagline: "不注册，靠私密链接分享",
  nameLabel: "书单名称",
  namePlaceholder: "例如：周末读书会",
  create: "创建书单",
  nameRequired: "请填写书单名称",
  memberNameRequired: "请填写成员名",
  loading: "加载中…",
  notFoundTitle: "找不到这个书单",
  notFoundDetail: "链接可能打错了，或书单不存在",
  backHome: "回首页",
  copyLink: "复制链接",
  share: "分享",
  members: "成员",
  addMember: "+ 加成员",
  addMemberTitle: "加成员",
  manageMember: "改名",
  memberNameLabel: "成员名",
  confirm: "确定",
  save: "保存",
  cancel: "取消",
  saved: "已保存",
  linkCopied: "已复制链接",
  noMembers: "还没有成员，先加一个再选「我是谁」",
  whoAmI: "我是谁",
  pickIdentity: "选择「我是谁」",
  enterList: "进入书单",
  currentIdentity: (name: string) => `当前：${name}`,
  switchIdentity: "切换身份",
  identityRequired: "请先选择「我是谁」",
  books: "书单",
  addBook: "加书",
  bookTitleLabel: "书名",
  bookTitlePlaceholder: "例如：三体",
  bookTitleRequired: "请填写书名",
  memberRequired: "请先选择「我是谁」",
  invalidScore: "请选择 1、2 或 3 分",
  scoreMustRead: "必读",
  scoreRecommend: "推荐阅读",
  scoreBoring: "无聊再读",
  myScore: (label: string) => `我的评分：${label}`,
  noScore: "未评分",
  rateBook: "给书打分",
  revokeScore: "撤销评分",
  noBooks: "还没有书，先加一本",
} as const;
