export const copy = {
  appName: "聚餐分账",
  tagline: "不注册，靠链接分享",
  nameLabel: "饭局名称",
  namePlaceholder: "例如：周五火锅",
  create: "创建饭局",
  nameRequired: "请填写饭局名称",
  personNameRequired: "请填写人名",
  personNameDuplicate: "这个名字已经有了",
  loading: "加载中…",
  notFoundTitle: "找不到这个饭局",
  notFoundDetail: "链接可能打错了，或饭局不存在",
  backHome: "回首页",
  copyLink: "复制链接",
  share: "分享",
  people: "参与人",
  addPerson: "+ 加人",
  addPersonTitle: "加人",
  managePerson: "管理此人",
  personNameLabel: "人名",
  confirm: "确定",
  save: "保存",
  cancel: "取消",
  deletePerson: "删除此人",
  saved: "已保存",
  linkCopied: "已复制链接",
  deletePersonConfirm: (name: string) => `确定删除「${name}」？`,
  personOnExpense: "这个人已出现在账目中，请先改账再删除",
  noPeople: "还没有参与人，点「+ 加人」",
  needPeopleFirst: "请先加人",
  expenses: "账目",
  noExpenses: "还没有账目，点下方「记一笔」",
  settlement: "结算",
  noBills: "还没有账目",
  allSettled: "已经两清，不需要转账",
  addExpense: "记一笔",
  editExpense: "编辑账目",
  expenseDescriptionLabel: "说明",
  expenseAmountLabel: "金额",
  expensePayerLabel: "付款人",
  expenseShareesLabel: "分摊人",
  amountInvalid: "金额必须大于 0，最多两位小数",
  descriptionRequired: "请填写说明",
  payerRequired: "请选择付款人",
  shareesRequired: "请至少选择一个分摊人",
  deleteExpense: "删除这笔账",
  deleteExpenseConfirm: "确定删除这笔账？",
} as const;
