export const copy = {
  appName: "聚餐分账",
  tagline: "不注册，靠链接分享",
  nameLabel: "饭局名称",
  namePlaceholder: "例如：周五火锅",
  create: "创建饭局",
  nameRequired: "请填写饭局名称",
  loading: "加载中…",
  notFoundTitle: "找不到这个饭局",
  notFoundDetail: "链接可能打错了，或饭局不存在",
  backHome: "回首页",
  copyLink: "复制链接",
  share: "分享",
  people: "参与人",
  addPerson: "+ 加人",
  noPeople: "还没有参与人，点「+ 加人」",
  expenses: "账目",
  noExpenses: "还没有账目，点下方「记一笔」",
  settlement: "结算",
  noBills: "还没有账目",
  addExpense: "记一笔",
} as const;
